= Antora Boilerplate


[[section-architecture-constraints]]
== Architecture Constraints


[role="arc42help"]
****
.Contents
Any requirement that constrains software architects in their freedom of design and implementation decisions or decision about the development process. These constraints sometimes go beyond individual systems and are valid for whole organizations and companies.

.Motivation
Architects should know exactly where they are free in their design decisions and where they must adhere to constraints.
Constraints must always be dealt with; they may be negotiable, though.

.Form
Simple tables of constraints with explanations.
If needed you can subdivide them into
technical constraints, organizational and political constraints and
conventions (e.g. programming or versioning guidelines, documentation or naming conventions)
****

== Введение и цели

[role="arc42help"]
****
Опишите релевантные требования и движущие факторы, которые должны быть приняты во внимание командой разработки. Они включают в себя

* основные бизнес-цели, основные возможности системы и функциональные требования к системе
* качественные цели для архитектуры
* основных стейкхолдеров и их ожидания от системы
****

=== Обзор требований

[role="arc42help"]
****
.Содержание
Краткое описание функциональных требований, движущих сил, выжимка (или обобщенное описание) общих
требований к системе. Ссылки на документы с требованиями с указанием версии и расположения документов (если, конечно, они у вас есть).

.Мотивация
С точки зрения конечных пользователей, система создается или дорабатывается, чтобы 
улучшить поддержку бизнес-активностей и/или для улучшения качества системы в целом.

.Форма
Краткое текстовое описание, возможно, в формате таблицы со сценариями использования.
Старайтесь быть лаконичными. Необходимо соблюсти баланс читабельности и избыточности, 
не надо переписывать здесь весь список требований из связанных документов.
****
